<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HolidaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('holidays')->delete();
        
        \DB::table('holidays')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'New Year\'s Day',
                'description' => 'New Year’s Day is the first day of the year, or January 1, in the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-01-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/new-year-day',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Anniversary of the Independence Manifesto',
                'description' => 'Anniversary of the Independence Manifesto is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-01-11',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-independence-manifesto',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Daylight Saving Time ends',
                'description' => 'Daylight Saving Time ends in Morocco',
                'country' => 'Morocco',
                'date' => '2023-03-19',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'March Equinox',
            'description' => 'March Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-03-20',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/vernal-equinox',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ramadan Start',
                'description' => 'Ramadan is a period of prayer, reflection and fasting for many Muslims worldwide. It is the ninth month in the Islamic calendar.',
                'country' => 'Morocco',
                'date' => '2023-03-23',
                'type' => 'Observance',
                'primary_type' => 'Observance',
                'urlid' => 'morocco/ramadan-begins',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Eid al-Fitr',
                'description' => 'Eid al-Fitr is a holiday to mark the end of the Islamic month of Ramadan, during which Muslims fast during the hours of daylight.',
                'country' => 'Morocco',
                'date' => '2023-04-22',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr-1',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Daylight Saving Time starts',
                'description' => 'Daylight Saving Time starts in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a government holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-24',
                'type' => 'Common local holiday',
                'primary_type' => 'Government Holiday',
                'urlid' => 'morocco/eid-al-fitr-2',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Labour Day/May Day',
                'description' => 'Labor Day, International Workers\' Day, and May Day, is a day off for workers in many countries around the world.',
                'country' => 'Morocco',
                'date' => '2023-05-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/labour-day',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'June Solstice',
            'description' => 'June Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-06-21',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/june-solstice',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Eid al-Adha',
            'description' => 'Eid al-Adha (Id ul-Adha) is an Islamic festival falling on the 10th day of the month of Dhul Hijja (Thou al-Hijja) to commemorate the willingness of Ibrahim (Abraham) to sacrifice his son.',
                'country' => 'Morocco',
                'date' => '2023-06-29',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Eid al-Adha holiday',
                'description' => 'Eid al-Adha holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-06-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha-2',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Hijra New Year',
                'description' => 'Muharram is the first month of the Islamic calendar and a time of remembrance or mourning.',
                'country' => 'Morocco',
                'date' => '2023-07-19',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/muharram-new-year',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Feast of the Throne',
                'description' => 'Feast of the Throne is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-07-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/feast-of-the-throne',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Anniversary of the Recovery Oued Ed-Dahab',
                'description' => 'Anniversary of the Recovery Oued Ed-Dahab is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-14',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-recovery-qued-ed-dahib',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Anniversary of the Revolution of the King and the People',
                'description' => 'Anniversary of the Revolution of the King and the People is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-20',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-revolution-king-and-people',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Youth Day',
                'description' => 'Youth Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-21',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/youth-day',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'September Equinox',
            'description' => 'September Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-09-23',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/autumnal-equniox',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'The Prophet Muhammad\'s Birthday',
                'description' => 'Mawlid, or Milad, marks the birth of the Islamic prophet Muhammed, or Mohamed, in the year 570 of the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-09-27',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'The Prophet Muhammad\'s Birthday Holiday',
                'description' => 'The Prophet Muhammad\'s Birthday Holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-09-28',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday-2',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Anniversary of the Green March',
                'description' => 'Anniversary of the Green March is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-06',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-green-march',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Independence Day',
                'description' => 'Independence Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-18',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/independence-day',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'December Solstice',
            'description' => 'December Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-12-22',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/december-solstice',
                'created_at' => '2023-05-11 10:55:51',
                'updated_at' => '2023-05-11 10:55:51',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'New Year\'s Day',
                'description' => 'New Year’s Day is the first day of the year, or January 1, in the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-01-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/new-year-day',
                'created_at' => '2023-05-11 10:56:37',
                'updated_at' => '2023-05-11 10:56:37',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Anniversary of the Independence Manifesto',
                'description' => 'Anniversary of the Independence Manifesto is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-01-11',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-independence-manifesto',
                'created_at' => '2023-05-11 10:56:37',
                'updated_at' => '2023-05-11 10:56:37',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Daylight Saving Time ends',
                'description' => 'Daylight Saving Time ends in Morocco',
                'country' => 'Morocco',
                'date' => '2023-03-19',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:56:37',
                'updated_at' => '2023-05-11 10:56:37',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'March Equinox',
            'description' => 'March Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-03-20',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/vernal-equinox',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Ramadan Start',
                'description' => 'Ramadan is a period of prayer, reflection and fasting for many Muslims worldwide. It is the ninth month in the Islamic calendar.',
                'country' => 'Morocco',
                'date' => '2023-03-23',
                'type' => 'Observance',
                'primary_type' => 'Observance',
                'urlid' => 'morocco/ramadan-begins',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Eid al-Fitr',
                'description' => 'Eid al-Fitr is a holiday to mark the end of the Islamic month of Ramadan, during which Muslims fast during the hours of daylight.',
                'country' => 'Morocco',
                'date' => '2023-04-22',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr-1',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Daylight Saving Time starts',
                'description' => 'Daylight Saving Time starts in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a government holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-24',
                'type' => 'Common local holiday',
                'primary_type' => 'Government Holiday',
                'urlid' => 'morocco/eid-al-fitr-2',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Labour Day/May Day',
                'description' => 'Labor Day, International Workers\' Day, and May Day, is a day off for workers in many countries around the world.',
                'country' => 'Morocco',
                'date' => '2023-05-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/labour-day',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'June Solstice',
            'description' => 'June Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-06-21',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/june-solstice',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Eid al-Adha',
            'description' => 'Eid al-Adha (Id ul-Adha) is an Islamic festival falling on the 10th day of the month of Dhul Hijja (Thou al-Hijja) to commemorate the willingness of Ibrahim (Abraham) to sacrifice his son.',
                'country' => 'Morocco',
                'date' => '2023-06-29',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Eid al-Adha holiday',
                'description' => 'Eid al-Adha holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-06-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha-2',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Hijra New Year',
                'description' => 'Muharram is the first month of the Islamic calendar and a time of remembrance or mourning.',
                'country' => 'Morocco',
                'date' => '2023-07-19',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/muharram-new-year',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Feast of the Throne',
                'description' => 'Feast of the Throne is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-07-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/feast-of-the-throne',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Anniversary of the Recovery Oued Ed-Dahab',
                'description' => 'Anniversary of the Recovery Oued Ed-Dahab is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-14',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-recovery-qued-ed-dahib',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Anniversary of the Revolution of the King and the People',
                'description' => 'Anniversary of the Revolution of the King and the People is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-20',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-revolution-king-and-people',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Youth Day',
                'description' => 'Youth Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-21',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/youth-day',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'September Equinox',
            'description' => 'September Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-09-23',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/autumnal-equniox',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'The Prophet Muhammad\'s Birthday',
                'description' => 'Mawlid, or Milad, marks the birth of the Islamic prophet Muhammed, or Mohamed, in the year 570 of the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-09-27',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'The Prophet Muhammad\'s Birthday Holiday',
                'description' => 'The Prophet Muhammad\'s Birthday Holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-09-28',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday-2',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Anniversary of the Green March',
                'description' => 'Anniversary of the Green March is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-06',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-green-march',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Independence Day',
                'description' => 'Independence Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-18',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/independence-day',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'December Solstice',
            'description' => 'December Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-12-22',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/december-solstice',
                'created_at' => '2023-05-11 10:56:38',
                'updated_at' => '2023-05-11 10:56:38',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'New Year\'s Day',
                'description' => 'New Year’s Day is the first day of the year, or January 1, in the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-01-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/new-year-day',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Anniversary of the Independence Manifesto',
                'description' => 'Anniversary of the Independence Manifesto is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-01-11',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-independence-manifesto',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Daylight Saving Time ends',
                'description' => 'Daylight Saving Time ends in Morocco',
                'country' => 'Morocco',
                'date' => '2023-03-19',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'March Equinox',
            'description' => 'March Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-03-20',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/vernal-equinox',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Ramadan Start',
                'description' => 'Ramadan is a period of prayer, reflection and fasting for many Muslims worldwide. It is the ninth month in the Islamic calendar.',
                'country' => 'Morocco',
                'date' => '2023-03-23',
                'type' => 'Observance',
                'primary_type' => 'Observance',
                'urlid' => 'morocco/ramadan-begins',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Eid al-Fitr',
                'description' => 'Eid al-Fitr is a holiday to mark the end of the Islamic month of Ramadan, during which Muslims fast during the hours of daylight.',
                'country' => 'Morocco',
                'date' => '2023-04-22',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-fitr-1',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Daylight Saving Time starts',
                'description' => 'Daylight Saving Time starts in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-23',
                'type' => 'Clock change/Daylight Saving Time',
                'primary_type' => 'Clock change/Daylight Saving Time',
                'urlid' => NULL,
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Eid al-Fitr holiday',
                'description' => 'Eid al-Fitr holiday is a government holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-04-24',
                'type' => 'Common local holiday',
                'primary_type' => 'Government Holiday',
                'urlid' => 'morocco/eid-al-fitr-2',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Labour Day/May Day',
                'description' => 'Labor Day, International Workers\' Day, and May Day, is a day off for workers in many countries around the world.',
                'country' => 'Morocco',
                'date' => '2023-05-01',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/labour-day',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'June Solstice',
            'description' => 'June Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-06-21',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/june-solstice',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Eid al-Adha',
            'description' => 'Eid al-Adha (Id ul-Adha) is an Islamic festival falling on the 10th day of the month of Dhul Hijja (Thou al-Hijja) to commemorate the willingness of Ibrahim (Abraham) to sacrifice his son.',
                'country' => 'Morocco',
                'date' => '2023-06-29',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Eid al-Adha holiday',
                'description' => 'Eid al-Adha holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-06-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/eid-al-adha-2',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Hijra New Year',
                'description' => 'Muharram is the first month of the Islamic calendar and a time of remembrance or mourning.',
                'country' => 'Morocco',
                'date' => '2023-07-19',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/muharram-new-year',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Feast of the Throne',
                'description' => 'Feast of the Throne is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-07-30',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/feast-of-the-throne',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Anniversary of the Recovery Oued Ed-Dahab',
                'description' => 'Anniversary of the Recovery Oued Ed-Dahab is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-14',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-recovery-qued-ed-dahib',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Anniversary of the Revolution of the King and the People',
                'description' => 'Anniversary of the Revolution of the King and the People is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-20',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-revolution-king-and-people',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Youth Day',
                'description' => 'Youth Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-08-21',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/youth-day',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'September Equinox',
            'description' => 'September Equinox in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-09-23',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/autumnal-equniox',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'The Prophet Muhammad\'s Birthday',
                'description' => 'Mawlid, or Milad, marks the birth of the Islamic prophet Muhammed, or Mohamed, in the year 570 of the Gregorian calendar.',
                'country' => 'Morocco',
                'date' => '2023-09-27',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'The Prophet Muhammad\'s Birthday Holiday',
                'description' => 'The Prophet Muhammad\'s Birthday Holiday is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-09-28',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/prophet-birthday-2',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Anniversary of the Green March',
                'description' => 'Anniversary of the Green March is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-06',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/anniversary-green-march',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Independence Day',
                'description' => 'Independence Day is a national holiday in Morocco',
                'country' => 'Morocco',
                'date' => '2023-11-18',
                'type' => 'National holiday',
                'primary_type' => 'National holiday',
                'urlid' => 'morocco/independence-day',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'December Solstice',
            'description' => 'December Solstice in Morocco (Casablanca)',
                'country' => 'Morocco',
                'date' => '2023-12-22',
                'type' => 'Season',
                'primary_type' => 'Season',
                'urlid' => 'seasons/december-solstice',
                'created_at' => '2023-05-11 10:57:03',
                'updated_at' => '2023-05-11 10:57:03',
            ),
        ));
        
        
    }
}